### ISSUE TITLE
Use Label Statistics to populate VoxelIntensityRange in GLCM and GLRLM

### ISSUE THREAD

**Issue by phcerdan** [Kitware/BoneTextureExtension#15]
Right now getting this right is tricky. The number of bins and the voxel intensity range are connected for the [texture analysis](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Numerics/Statistics/include/itkScalarImageToTextureFeaturesFilter.h).

Ideally we want to select only the relevant voxel range inside our mask. But if the range is too broad, the bins of the histogram should be increased.
The min/max voxel range can be computed manually using Label Statistics Module.
Also ideally, and for consistent results between different experiments, number of bins can be tweaked based on the range span. Something like 100 bins per 1000 grayscale value difference maybe:
```
bins = 100 * ceil(abs(maxIntensityValue - minIntensityValue)/1000)
```

This is just to set more meaningful default parameters, the user can still tweak them.

@bpaniagua

**Comment by phcerdan** [comment]
Also pinging @thewtex for extra feedback. Sorry Matt for pinging you too much today!

**Comment by thewtex** [comment]
Sound like a good approach to me -- fewer parameters to manually determine and specify!
