### ISSUE TITLE
Bonetexture in 3D Slicer won’t compute/display feature maps

### ISSUE THREAD

**Issue by lcw918** [Kitware/BoneTextureExtension#22]
3dslicer: 4.10.02
Dell G7  7590
Win10 10.0.17763

**Comment by bpaniagua** [comment]
Similar problem.

Slicer version: 4.11.0-2019-12-02 r28659
OS: Ubuntu 16.04
Behavior: Maps are computed, but not displayed.
Error message:
```
  File "/home/bpaniagua/.config/NA-MIC/Extensions-28659/BoneTextureExtension/lib/Slicer-4.11/qt-scripted-modules/BoneTexture.py", line 254, in onFeatureSetChanged
    if node.GetDisplayNode().GetInputImageData().GetNumberOfScalarComponents() == 8:
AttributeError: 'NoneType' object has no attribute 'GetNumberOfScalarComponents'
```

**Comment by bpaniagua** [comment]
Probably related to #27

**Comment by muratmaga** [comment]
Any update on this? I have the same issue. 4.11.0-2020-06-15 r29148 / 7a36988
 (windows).

**Comment by muratmaga** [comment]
Also any plan to update the extension such that it uses segmentations directly (as oppose to exporting them to a labelmap first)?

**Comment by bpaniagua** [comment]
@muratmaga, @sjh26 is looking into this. Stay tuned!

**Comment by sjh26** [comment]
How long are the texture maps supposed to take to compute?  This is at least part of the problem.  The UI gives no indication that the CLI is running, and doesn't lock out, so you can try to select and show the feature maps before it is finished, which causes the python traceback.  Once it actually finishes, thats when I get the error below:

```
Missing 'DWMRI_b-value' tag!


vtkMRMLDiffusionWeightedVolumeNode: Cannot parse Diffusion Information

```

**Comment by sjh26** [comment]
The tag appears to be correctly set in the code.  I haven't been able to verify that the file is correctly generated yet.

**Comment by bpaniagua** [comment]
Yes, @sjh26 

We decided to generate these maps as ND volumes, where N is the number of features. This was so we could facilitate their statistical processing, in which each data object was the Nx1 textural pixel signature (that we used to classify areas within the same image)

In order to display ND volumes in Slicer, back in the days we did not have a structure that we could readily use, so we just told Slicer these were DWI images (that are basically ND images, where N is the number of gradients). The only problem with that it is that we needed a b-value, that we were just bogus setting to a constant value.


I am not sure why that stopped working.

HTH
Bea

**Comment by muratmaga** [comment]
Checking in for an update?

**Comment by bpaniagua** [comment]
We are experiencing some uncanny problem.
It works on the stable version, have you tried there?

**Comment by muratmaga** [comment]
Stable is too stale for our work (we need the new markups infrastructure). But I will let my collaborators now.

**Comment by sjh26** [comment]
So, you guys are reporting that it works in the stable version, but this issue was originally opened on a bug from the stable version (4.10.1)

**Comment by muratmaga** [comment]
I haven't tried with the stable, as we don't use it in the lab. All I know it doesn't work with preview versions.

**Comment by muratmaga** [comment]
Checking in. We need to use this tool for a project. What's the recommendation, use the stable?

**Comment by sjh26** [comment]
Yes, use the stable for now.  I haven't had much success tracking down the source of the file read error.

**Comment by muratmaga** [comment]
Checking in whether there are any updates on this? SOme people has shown interest in this extension in SlicerMorph workshop.

**Comment by bpaniagua** [comment]
We will be fixing this module soon, expect movement in the scope of the next month (hopefully)

**Comment by StewartMW1234** [comment]
Hi. Any news on that topic? I work with a Mac. Tried the nightly build, stable version and 4.10.2, but none of the softwares gives me the feature maps. I also tried on a Windows machine at the hospital where I was able to install slicer, but can't access the extensions store. Not through the software nor through the homepage for manual installation. Getting really annoying.....

**Comment by bpaniagua** [comment]
Sorry for the delay, we will look into this shortly.
