### ISSUE TITLE
AttributeError: module 'VectorToScalarVolume' has no attribute 'VectorToScalarVolumeConversionMethodWidget'

### ISSUE THREAD

**Issue by thangngoc89** [Kitware/BoneTextureExtension#43]
I encountered an error with BoneTexture module, it’s probably because it wasn’t updated with the latest code changes from 3D Slicer.

As soon as I load the BoneTexture module, an error was thrown in the console and none of the function would work.

```
Traceback (most recent call last):

File "/Applications/Slicer.app/Contents/Extensions-31938/BoneTextureExtension/lib/Slicer-5.4/qt-scripted-modules/BoneTexture.py", line 155, in setup

self.vectorToScalarVolumeConversionWidget = VectorToScalarVolume.VectorToScalarVolumeConversionMethodWidget()

AttributeError: module 'VectorToScalarVolume' has no attribute 'VectorToScalarVolumeConversionMethodWidget'
```

I’ve looked around the commit history of Slicer and VectorToScalarVolumeConversionMethodWidget was removed in [this commit in 2022](https://github.com/Slicer/Slicer/commit/41adaa558f44e2cbe5d06053fd7b79b473e431e0#diff-9644ea9d931812f2dca3ce5c4ed35b5e15dc1518ea63de8b3967908a324d8379L162)

I’ve tested this on Windows, MacOS (M2) and Linux, it’s throwing the same error.
I’ve tested this multiple stable releases from latest preview (5.5.0-2023-11-14) to 5.0.2.
The last working 3D Slicer version for this extension is 5.0.3.

**Comment by bpaniagua** [comment]
@thangngoc89 thanks for reporting.

@sjh26 I confirmed this problem in my macos computer as well. Could you please have a look?
<img width="878" alt="Screenshot 2023-11-30 at 2 43 17 PM" src="https://github.com/Kitware/BoneTextureExtension/assets/2599368/7db4d880-ee99-4e29-8979-21227669aa7a">
